name: semgrep-rules-test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  self-test:
    runs-on: ubuntu-latest
    name: run semgrep rules tests
    steps:
      - uses: actions/checkout@v2
      - name: run test
        id: semgrep-tests
        uses: returntocorp/semgrep-rules-test-action@master
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests
          path: ${{ steps.semgrep-tests.outputs.output_dir }}
